version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  github-release: h-matsuo/github-release@0.1.1

jobs:
  build-test:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Django checking
          command: python manage.py check

  publish-github-release:
    description: Create dummy file and publish a new release tagged `v1.0.2`.
    executor: github-release/default
    steps:
      - run:
          command: |
            mkdir artifacts
            echo dummy > ./artifacts/file
      - github-release/create:
          tag: v1.0.2
          title: Version v1.0.2
          description: This release is version v1.0.2 .
          file-path: ./artifacts/file

  deploy:
    executor: heroku/default
    environment:
      HEROKU_APP_NAME: fa-dev-example
      HEROKU_API_KEY: 990c573f-bb6b-4442-8a4d-74c4fa5d266b
    steps:
      - checkout
      - heroku/install
      - run:
          name: "Check heroku user"
          command: |
            heroku create fa-1336-dev-example --buildpack heroku/python
            git remote add heroku https://git.heroku.com/fa-1336-dev-example.git
            git push heroku main
#      - heroku/deploy-via-git


workflows:
  build-test-deploy:
    jobs:
      - deploy
#      - build-test
#      - publish-github-release:
#          requires:
#            - build-test
#          filters:
#            branches:
#              only: main
#            tags:
#              only: /^\d+\.\d+\.\d+$/
#      - deploy:
#          requires:
#            - publish-github-release
#          filters:
#            branches:
#              only: main
