version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build-test:
    docker:
      - image: circleci/python:3.7-node
        environment:
          HEROKU_APP_NAME: fa-dev-example
          HEROKU_API_KEY: 990c573f-bb6b-4442-8a4d-74c4fa5d266b
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Django checking
          command: python manage.py check

workflows:
  build-test-deploy:
    jobs:
      - build-test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          job_type: deployment
          requires:
            - build-test
          filters:
            branches:
              only: main
