version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build-test:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Django checking
          command: python manage.py check

  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/


  deploy:
    executor: heroku/default
    environment:
      HEROKU_APP_NAME: fa-dev-example
      HEROKU_API_KEY: 990c573f-bb6b-4442-8a4d-74c4fa5d266b
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git


workflows:
  build-test-deploy:
    jobs:
      - build-test
      - publish-github-release:
          requires:
            - build-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
