version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build-test:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: pip install
      - run:
          name: Checking Django
          command: python manage.py check

workflows:
  build-test-deploy:
    jobs:
      - build-test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main
