--- 
jobs: 
  build-test: 
    docker: 
      - 
        image: "circleci/python:3.7-node"
    steps: 
      - checkout
      - 
        run: 
          command: "pip install -r requirements.txt"
          name: "Install Dependencies"
      - 
        run: 
          command: "python manage.py check"
          name: "Django checking"
  deploy: 
    environment: 
      HEROKU_API_KEY: 990c573f-bb6b-4442-8a4d-74c4fa5d266b
      HEROKU_APP_NAME: fa-dev-example
    executor: heroku/default
    steps: 
      - checkout
      - heroku/install
      - 
        run: 
          command: "heroku auth:whoami\n"
          name: "Check heroku user"
  publish-github-release: 
    description: "Create dummy file and publish a new release tagged `v1.0.1`."
    executor: github-release/default
    steps: 
      - 
        run: 
          command: |
              mkdir artifacts
              echo dummy > ./artifacts/file
      - 
        run: 
          command: "echo 'export GITHUB_TOKEN=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' >> $BASH_ENV"
          name: "Setup custom environment variables"
      - 
        github-release/create: 
          description: "This release is version v1.0.1 ."
          environment: 
            GITHUB_TOKEN: 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
          file-path: ./artifacts/file
          tag: v1.0.1
          title: "Version v1.0.1"
orbs: 
  github-release: h-matsuo/github-release@0.1.1
  heroku: circleci/heroku@0.0.10
version: 2.1
workflows: 
  build-test-deploy: 
    jobs: 
      - build-test
      - 
        publish-github-release: 
          filters: 
            branches: 
              only: main
            tags: 
              only: /^\d+\.\d+\.\d+$/
          requires: 
            - build-test
      - 
        deploy: 
          filters: 
            branches: 
              only: main
          requires: 
            - publish-github-release
