version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  github: haskell-works/github-release@1.3.3

jobs:
  build-test:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Django checking
          command: python manage.py check

#  publish-github-release:
#    docker:
#      - image: circleci/golang:1.8
#        environment:
#          GITHUB_TOKEN: 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
#          VERSION: v1.0.1
#    steps:
#      - attach_workspace:
#          at: ./artifacts
#      - run:
#          name: "Publish Release on GitHub"
#          command: |
#            go get github.com/tcnksm/ghr
#            VERSION=$(my-binary --version)
#            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
  publish-github-release:
    executor: github/default
    environment:
      GITHUB_TOKEN: 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
      VERSION: v1.0.1
    steps:
      - github/release

  deploy:
    executor: heroku/default
    environment:
      HEROKU_APP_NAME: fa-dev-example
      HEROKU_API_KEY: 990c573f-bb6b-4442-8a4d-74c4fa5d266b
    steps:
      - checkout
      - heroku/install
      - run:
          name: "Check heroku user"
          command: |
            heroku auth:whoami
#      - heroku/deploy-via-git


workflows:
  build-test-deploy:
    jobs:
      - build-test
      - publish-github-release:
          tag: v$CIRCLE_BUILD_NUM
          title: Release v$CIRCLE_BUILD_NUM
          requires:
            - build-test
          filters:
            branches:
              only: main
            tags:
              only: /^\d+\.\d+\.\d+$/
      - deploy:
          requires:
            - publish-github-release
          filters:
            branches:
              only: main
