version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  github-release: h-matsuo/github-release@0.1.1

jobs:
  build-test:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Django checking
          command: python manage.py check

  publish-github-release:
    description: Create dummy file and publish a new release tagged `v0.0.${CIRCLE_BUILD_NUM}`.
    executor: github-release/default
    steps:
      - run:
          command: |
            mkdir artifacts
            echo dummy > ./artifacts/file
      - github-release/create:
          tag: v0.0.${CIRCLE_BUILD_NUM}
          title: Version v0.0.${CIRCLE_BUILD_NUM}
          description: This release is https://fa-${CIRCLE_BUILD_NUM}-dev-example.herokuapp.com
          file-path: ./artifacts/file

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: "Create candidate release for development"  
          command: |
            heroku create fa-${CIRCLE_BUILD_NUM}-dev-example --buildpack heroku/python
            git remote set-url heroku https://:git.heroku.com/fa-${CIRCLE_BUILD_NUM}-dev-example.git
            export HEROKU_APP_NAME=fa-${CIRCLE_BUILD_NUM}-dev-example
      #            git push heroku main
      - heroku/deploy-via-git


workflows:
  build-test-deploy:
    jobs:
      - deploy
#      - build-test
#      - publish-github-release:
#          requires:
#            - build-test
#          filters:
#            branches:
#              only: main
#            tags:
#              only: /^\d+\.\d+\.\d+$/
#      - deploy:
#          requires:
#            - publish-github-release
#          filters:
#            branches:
#              only: main
